# -*- coding: utf-8 -*-
"""run_app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZpL9zXPhUx3zlmamLm7h3WaugRsQiCb
"""

!streamlit run streamlit_app.py